services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        # [Choice] Python version: 3, 3.8, 3.7, 3.6
        VARIANT: "3.11"
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - .:/workspace

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Request GPUs: use Docker Compose v2.x syntax
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

